# https://www.osbuild.org/guides/blueprint-reference/blueprint-reference.html

#
# Base definition
#
name = "base-image"
description = "RHEL 8.7 Minimal Install"
version = "2022.12.08"
distro = "rhel-87"

#
# Boot parameters
#
[customizations.kernel]
append = "net.ifnames.prefix=net quiet systemd.show_status=yes"

#
# Filesystem
#
[[customizations.filesystem]]
mountpoint = "/boot"

size = 1073741824
[[customizations.filesystem]]

mountpoint = "swap"

size = 2147483648
[[customizations.filesystem]]
mountpoint = "/"
### 8G 
size = 8589934592
[[customizations.filesystem]]
mountpoint = "/home"

size = 1073741824
[[customizations.filesystem]]

mountpoint = "/tmp"

size = 1073741824
[[customizations.filesystem]]
mountpoint = "/var"

size = 8589934592
[[customizations.filesystem]]
mountpoint = "/var/log"

size = 2147483648
[[customizations.filesystem]]
mountpoint = "/var/log/audit"

size = 1073741824
[[customizations.filesystem]]
mountpoint = "/var/tmp"

size = 1073741824

#
# Locale
#
[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "us"

#
# Timezone
#
[customizations.timezone]
timezone = "US/Eastern"
ntpservers = ["0.north-america.pool.ntp.org", "1.north-america.pool.ntp.org"]

#
# Services
#
[customizations.services]
enabled = ["sshd", "tuned"]

#
# Firewall
#
[customizations.firewall.services]
enabled = ["ssh"]

# Groups
[[groups]]
name="Minimal Install"

#
# Packages
#
[[packages]]
name = "bash-completion"
version = "*"
[[packages]]
name = "bzip2"
version = "*"
#[[packages]]
#name = "cloud-init"
#version = "*"
#[[packages]]
#name = "cloud-utils-growpart"
#version = "*"
[[packages]]
name = "firewalld"
version = "*"
[[packages]]
name = "man-pages"
version = "*"
[[packages]]
name = "nano"
version = "*"
[[packages]]
name = "python3"
version = "*"
[[packages]]
name = "python3-libselinux"
version = "*"
[[packages]]
name = "setools-console"
version = "*"
[[packages]]
name = "tar"
version = "*"
[[packages]]
name = "tuned"
version = "*"
[[packages]]
name = "vim-enhanced"
version = "*"
[[packages]]
name = "yum-utils"
version = "*"


#
# Security compliance
#
[[packages]]
name = "aide"
version = "*"
[[packages]]
name = "openscap"
version = "*"
[[packages]]
name = "openscap-scanner"
version = "*"
[[packages]]
name = "scap-security-guide"
version = "*"

# Ansible
[[packages]]
name = "ansible"
version = "*"

# Git
[[packages]]
name = "git"
version = "*"


[customizations.openscap]
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
profile_id = "xccdf_org.ssgproject.content_profile_stig_gui"
