- name: Build RHEL image with Image Builder
  hosts: all
  become: true
  vars:
    rhel_image_update_host: false
    rhel_image_create_user: false
    rhel_image_git_remote_repo: file:///tmp/rhel-image-blueprints.git
    rhel_image_git_repo_checkout: master
    rhel_image_blueprint: base-image
    rhel_image_size_kb: 20480
    rhel_image_output_type: ami
    rhel_image_download_dir: /tmp/images
  tasks:
    - name: Install myllynen.rhel_image role
      become: true
      command: ansible-galaxy install myllynen.rhel_image
    - name: Build RHEL image
      include_role:
        name: myllynen.rhel_image.rhel_image
