---
- name: Build RHEL image with Image Builder
  hosts: localhost
  become: true
  vars:
    rhel_image_create_user: false
    rhel_image_git_remote_repo: file:///tmp/rhel-image-blueprints.git
    rhel_image_git_repo_checkout: master
    rhel_image_blueprint: base-image
    rhel_image_size_kb: 20480
    rhel_image_output_type: ami
    rhel_image_download_dir: /tmp/images
  tasks:
    - name: Install Git
      become: true
      package:
        name: git
        state: present
    - name: Install myllynen.rhel_image collection
      command: ansible-galaxy collection install git+https://github.com/hasib-haque/rhel-image.git,master
